CREATE TABLE IF NOT EXISTS trips (
    id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    author_name TEXT,
    title TEXT NOT NULL,
    start_location TEXT NOT NULL,
    destination TEXT NOT NULL,
    route_mode TEXT NOT NULL,
    adventure_level INTEGER NOT NULL DEFAULT 50,
    budget_per_person INTEGER NOT NULL DEFAULT 0,
    travellers INTEGER NOT NULL DEFAULT 1,
    start_date TEXT,
    end_date TEXT,
    start_time TEXT,
    end_time TEXT,
    preferences JSONB NOT NULL DEFAULT '[]'::jsonb,
    route JSONB NOT NULL DEFAULT '{}'::jsonb,
    itinerary JSONB NOT NULL DEFAULT '[]'::jsonb,
    candidate_places JSONB NOT NULL DEFAULT '[]'::jsonb,
    cost_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
